pragma solidity ^0.5.0;
// Define a contract 'Supplychain'

import "CustomerRole.sol";
import "FarmerRole.sol";
import "ShipperRole.sol";
import "SupermarketRole.sol";
import "Ownable.sol";


contract SupplyChain is Ownable, CustomerRole, FarmerRole, ShipperRole, SupermarketRole {

    // Define 'owner'
    address owner;

    // Define a variable called 'upc' for Universal Product Code (UPC)
    uint  upc;

    // Define a variable called 'sku' for Stock Keeping Unit (SKU)
    uint  sku;

    // Define a public mapping 'items' that maps the UPC to an CoconutUnit.
    mapping (uint => CoconutUnit) items;

    // Define a public mapping 'itemsHistory' that maps the UPC to an array of TxHash,
    // that track its journey through the supply chain -- to be sent from DApp.
    mapping (uint => string[]) itemsHistory;

    // Define enum 'State' with the following values:
    enum State {
        ReadyForHarvest, // 0
        Harvested,
        ForSaleByFarmer,
        SoldToBuyer,
        TransferredToBuyer,
        AwaitingShipping,
        Shipping,
        Shipped,
        ForSaleByBuyer,
        SoldToCustomer
    }

    State private constant DEFAULT_STATE = State.ReadyForHarvest;

    uint private constant MARKUP_FACTOR = 10;

    // Define a struct 'Item' with the following fields:
    struct CoconutUnit {
        uint    sku;  // Stock Keeping Unit (SKU)
        uint    upc; // Universal Product Code (UPC), generated by the Farmer, goes on the package, can be verified by the Customer
        address ownerID;  // Metamask-Ethereum address of the current owner as the product moves through the stages
        address originFarmerID; // Metamask-Ethereum address of the Farmer
        string  originFarmName; // Farmer Name
        string  originFarmInformation;  // Farmer Information
        string  originFarmLatitude; // Farm Latitude
        string  originFarmLongitude;  // Farm Longitude
        uint    productID;  // Product ID potentially a combination of upc + sku
        string  productNotes; // Product Notes
        uint    productPrice; // Product Price
        State   itemState;  // Product State as represented in the enum above
        address shipperID;  // Metamask-Ethereum address of the Shipper
        address superMarketID; // Metamask-Ethereum address of the Supermarket
        address customerID; // Metamask-Ethereum address of the Customer
    }

    event ReadyForHarvest(uint upc);
    event Harvested(uint upc);
    event ForSaleByFarmer(uint upc);
    event SoldToBuyer(uint upc);
    event TransferredToBuyer(uint upc);
    event AwaitingShipping(uint upc);
    event Shipping(uint upc);
    event Shipped(uint upc);
    event ForSaleByBuyer(uint upc);
    event SoldToCustomer(uint upc);

    // Define a modifer that checks to see if msg.sender == owner of the contract
    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }

    // Define a modifer that verifies the Caller
    modifier verifyCaller (address _address) {
        require(msg.sender == _address);
        _;
    }

    // Define a modifier that checks if the paid amount is sufficient to cover the price
    modifier paidEnough(uint _price) {
        require(msg.value >= _price);
        _;
    }

    // Define a modifier that checks the price and refunds the remaining balance
    modifier refundChange(uint _upc, address recepient) {
        _;
        uint _price = items[_upc].productPrice;
        uint amountToReturn = msg.value - _price;
        recepient.transfer(amountToReturn);
    }

    modifier readyForHarvest(uint _upc) {
        require(items[_upc].itemState == State.ReadyForHarvest);
        _;
    }

    // Define a modifier that checks if an item.state of a upc is Harvested
    modifier harvested(uint _upc) {
        require(items[_upc].itemState == State.Harvested);
        _;
    }

    modifier forSaleByFarmer(uint upc) {
        require(items[_upc].itemState == State.ForSaleByFarmer);
        _;
    }

    modifier soldToBuyer(uint upc) {
        require(items[_upc].itemState == State.SoldToBuyer);
        _;
    }

    modifier transferredToBuyer(uint upc) {
        require(items[_upc].itemState == State.TransferredToBuyer);
        _;
    }

    modifier awaitingShipping(uint upc) {
        require(items[_upc].itemState == State.AwaitingShipping);
        _;
    }

    modifier shipping(uint upc) {
        require(items[_upc].itemState == State.Shipping);
        _;
    }

    modifier shipped(uint upc) {
        require(items[_upc].itemState == State.Shipped);
        _;
    }

    modifier isForSaleByBuyer(uint upc) {
        require(items[_upc].itemState == State.ForSaleByBuyer);
        _;
    }

    modifier soldToCustomer(uint upc) {
        require(items[_upc].itemState == State.SoldToCustomer);
        _;
    }

    // In the constructor set 'owner' to the address that instantiated the contract
    // and set 'sku' to 1
    // and set 'upc' to 1
    constructor() public payable {
        owner = msg.sender;
        sku = 1;
        upc = 1;
    }

    // Define a function 'kill' if required
    function kill() public {
        if (msg.sender == owner) {
            selfdestruct(owner);
        }
    }

    function prepareForHarvest(uint _upc, address _originFarmerID, string memory _originFarmName,
        string memory _originFarmInformation,
        string  memory _originFarmLatitude, string  memory _originFarmLongitude, string memory _productNotes)
        public
        onlyFarmer
    {
        uint prodId = _upc*(max(1, 10^floor(log10(sku)))) + sku;
        items[_upc] = Item(sku, _upc, msg.sender, _originFarmerID, _originFarmName, _originFarmInformation,
        _originFarmLatitude, _originFarmLongitude, prodId, _productNotes);
        items[_upc].itemState = DEFAULT_STATE;
        sku = sku + 1;
        emit ReadyForHarvest(_upc);
    }

    // Define a function 'harvestItem' that allows a farmer to mark an item 'Harvested'
    function harvestItem(uint upc)
        public
        onlyFarmer
        readyForHarvest(upc)
    {
        items[upc].itemState = State.Harvested;
        emit Harvested(upc);
    }

    function putUpForSale(uint upc, uint price)
        public
        onlyFarmer
        harvested(upc)
    {
        require(price > 0, "Invalid price");
        items[upc].itemState = State.ForSaleByFarmer;
        items[upc].productPrice = price;
        emit ForSaleByFarmer(upc);
    }

    function buyerBuysCoconuts(uint upc)
        public
        onlySupermarket
        forSaleByFarmer(upc)
        payable
        paidEnough(items[upc].productPrice)
        refundChange(upc, msg.sender)
    {
        items[upc].itemState = State.SoldToBuyer;
        items[upc].superMarketID = msg.sender;
        items[upc].originFarmerID.transfer(items[upc].productPrice);
        emit SoldToBuyer(upc);
    }

    function transferToBuyer(uint upc)
    public
    onlySupermarket
    soldToBuyer(upc)
    {
        items[upc].itemState = State.TransferredToBuyer;
        items[upc].ownerID = msg.sender;
        emit TransferredToBuyer(upc);
    }

    function submitShipment(uint upc, address shipper)
    public
    onlySupermarket
    transferredToBuyer(upc)
    {
        items[upc].itemState = State.AwaitingShipping;
        items[upc].shipperID = shipper;
        items[upc].ownerID = shipper;
        emit AwaitingShipping(upc);
    }

    function ship(uint upc)
    public
    onlyShipper
    awaitingShipping(upc)
    {
        items[upc].itemState = State.Shipping;
        emit Shipping(upc);
    }

    function shipped(uint upc)
    public
    onlyShipper
    shipping(upc)
    {
        items[upc].itemState = State.Shipped;
        items[upc].ownerID = items[upc].superMarketID;
        emit Shipped(upc);
    }

    function forSaleByBuyer(uint upc)
    public
    onlySupermarket
    shipped(upc)
    {
        items[upc].itemState = State.ForSaleByBuyer;
        items[upc].productPrice = items[upc].productPrice * (1 + (MARKUP_FACTOR / 100));
        emit ForSaleByBuyer(upc);
    }

    function customerBuysCoconuts(uint upc)
        public
        onlyCustomer
        isForSaleByBuyer(upc)
        payable
        paidEnough(items[upc].productPrice)
        refundChange(upc, msg.sender)
    {
        items[upc].itemState = State.SoldToCustomer;
        items[upc].ownerID = msg.sender;
        items[_upc].customerID = msg.sender;
        items[upc].superMarketID.transfer(items[upc].productPrice);
        emit SoldToCustomer(upc);
    }

    function fetchItemBufferOne(uint _upc) public view returns
    (
        uint    itemSKU,
        uint    itemUPC,
        address ownerID,
        address originFarmerID,
        string  originFarmName,
        string  originFarmInformation,
        string  originFarmLatitude,
        string  originFarmLongitude
    )
    {
        itemSKU = items[_upc].sku;
        itemUPC = _upc;
        ownerID = items[_upc].ownerID;
        originFarmerID = items[_upc].originFarmerID;
        originFarmName = items[_upc].originFarmName;
        originFarmInformation = items[_upc].originFarmInformation;
        originFarmLatitude = items[_upc].originFarmLatitude;
        originFarmLongitude = items[_upc].originFarmLongitude;

        return
        (
            itemSKU,
            itemUPC,
            ownerID,
            originFarmerID,
            originFarmName,
            originFarmInformation,
            originFarmLatitude,
            originFarmLongitude
        );
    }

    // Define a function 'fetchItemBufferTwo' that fetches the data
    function fetchItemBufferTwo(uint _upc) public view returns
    (
        uint    itemSKU,
        uint    itemUPC,
        uint    productID,
        string  productNotes,
        uint    productPrice,
        uint    itemState,
        address shipperID,
        address superMarketID,
        address customerID
    )
    {
        itemSKU = items[_upc].sku;
        itemUPC = _upc;
        productID = items[_upc].productID;
        productNotes = items[_upc].productNotes;
        productPrice = items[_upc].productPrice;
        itemState = items[_upc].itemState;
        shipperID = items[_upc].shipperID;
        superMarketID = items[_upc].superMarketID;
        customerID = items[_upc].customerID;

        return
        (
            itemSKU,
            itemUPC,
            productID,
            productNotes,
            productPrice,
            itemState,
            shipperID,
            superMarketID,
            customerID
        );
    }

}
